<?php

return [
    'nuvemshop' => [
        'nome' => 'Nuvemshop',
        'complexidade_geral' => 'baixa',
        'possui_app_store' => true,
        'custo_apps_medio' => 'R$ 30-150/mês',
        'recursos' => [
            'kits' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Criar produto do tipo "Kit" no painel administrativo, selecionando os produtos que compõem o kit',
                'complexidade' => 'baixa',
                'tempo_estimado' => '30 minutos por kit',
            ],
            'assinatura' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'Assine Nuvemshop, Rebill',
                'como_fazer' => 'Instalar app de assinatura da loja de aplicativos e configurar produtos recorrentes',
                'complexidade' => 'baixa',
                'tempo_estimado' => '2-4 horas',
                'custo' => 'R$ 49-149/mês dependendo do app',
            ],
            'avise_me' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Ativar "Avise-me quando disponível" nas configurações de produto sem estoque',
                'complexidade' => 'baixa',
                'tempo_estimado' => '15 minutos',
            ],
            'cupom' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Marketing > Cupons de desconto > Criar cupom',
                'complexidade' => 'baixa',
                'tempo_estimado' => '10 minutos',
            ],
            'frete_gratis_condicional' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Configurações > Formas de envio > Criar regra de frete grátis acima de valor',
                'complexidade' => 'baixa',
                'tempo_estimado' => '15 minutos',
            ],
            'email_carrinho_abandonado' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Marketing > Automações > Ativar recuperação de carrinho abandonado',
                'complexidade' => 'baixa',
                'tempo_estimado' => '30 minutos',
            ],
            'quiz_personalizado' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'Typeform (embed), Octadesk',
                'como_fazer' => 'Criar quiz no Typeform e incorporar na loja via código HTML',
                'complexidade' => 'media',
                'tempo_estimado' => '4-8 horas',
            ],
        ],
    ],

    'vtex' => [
        'nome' => 'VTEX',
        'complexidade_geral' => 'alta',
        'possui_app_store' => true,
        'custo_apps_medio' => 'R$ 200-1000/mês',
        'recursos' => [
            'kits' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Usar recurso "Kit Look" ou "Bundle" no Catalog. Configurar em Produtos > Kits',
                'complexidade' => 'media',
                'tempo_estimado' => '1-2 horas por kit',
            ],
            'assinatura' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Módulo Subscriptions nativo da VTEX. Configurar em Pedidos > Assinaturas',
                'complexidade' => 'media',
                'tempo_estimado' => '1-2 dias para setup completo',
                'custo' => 'Incluso na plataforma (pode ter custo por transação)',
            ],
            'avise_me' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Componente "Availability Notify" nativo. Configurar no CMS ou Site Editor',
                'complexidade' => 'baixa',
                'tempo_estimado' => '1-2 horas',
            ],
            'cupom' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Promoções > Cupons. Criar cupom vinculado a promoção',
                'complexidade' => 'media',
                'tempo_estimado' => '30 minutos',
            ],
            'frete_gratis_condicional' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Promoções > Nova promoção > Frete grátis com condição de valor mínimo',
                'complexidade' => 'media',
                'tempo_estimado' => '1 hora',
            ],
            'email_carrinho_abandonado' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'VTEX Trigger, Konduto, edrone',
                'como_fazer' => 'Configurar trigger de carrinho abandonado no Master Data ou usar app especializado',
                'complexidade' => 'alta',
                'tempo_estimado' => '1-2 dias',
            ],
            'quiz_personalizado' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'VTEX IO custom app, Jebbit',
                'como_fazer' => 'Desenvolver componente custom em VTEX IO ou integrar ferramenta externa',
                'complexidade' => 'alta',
                'tempo_estimado' => '1-2 semanas',
            ],
        ],
    ],

    'shopify' => [
        'nome' => 'Shopify',
        'complexidade_geral' => 'media',
        'possui_app_store' => true,
        'custo_apps_medio' => 'US$ 20-100/mês',
        'recursos' => [
            'kits' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'Bundler, Bold Bundles, PickyStory',
                'como_fazer' => 'Instalar app de bundles da Shopify App Store. Configurar produtos em kits',
                'complexidade' => 'baixa',
                'tempo_estimado' => '2-4 horas',
                'custo' => 'US$ 15-50/mês',
            ],
            'assinatura' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'Recharge, Bold Subscriptions, Seal Subscriptions',
                'como_fazer' => 'Instalar app de subscription. Configurar produtos elegíveis e frequências',
                'complexidade' => 'media',
                'tempo_estimado' => '4-8 horas',
                'custo' => 'US$ 60-300/mês + % por transação',
            ],
            'avise_me' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'Back in Stock, Notify Me, Stockify',
                'como_fazer' => 'Instalar app de back-in-stock alerts na App Store',
                'complexidade' => 'baixa',
                'tempo_estimado' => '1-2 horas',
                'custo' => 'Gratuito até US$ 20/mês',
            ],
            'cupom' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Discounts > Create discount. Configurar código e regras',
                'complexidade' => 'baixa',
                'tempo_estimado' => '10 minutos',
            ],
            'frete_gratis_condicional' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Settings > Shipping > Criar zona com frete grátis condicional',
                'complexidade' => 'baixa',
                'tempo_estimado' => '30 minutos',
            ],
            'email_carrinho_abandonado' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Settings > Checkout > Configurar abandoned checkout emails (até 3 emails)',
                'complexidade' => 'baixa',
                'tempo_estimado' => '1 hora',
            ],
            'quiz_personalizado' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'Octane AI, Quiz Kit, Product Recommendation Quiz',
                'como_fazer' => 'Instalar app de quiz e configurar perguntas e recomendações de produto',
                'complexidade' => 'media',
                'tempo_estimado' => '4-8 horas',
                'custo' => 'US$ 30-100/mês',
            ],
        ],
    ],

    'tray' => [
        'nome' => 'Tray',
        'complexidade_geral' => 'media',
        'possui_app_store' => true,
        'custo_apps_medio' => 'R$ 50-200/mês',
        'recursos' => [
            'kits' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Produtos > Novo produto > Tipo "Kit/Combo". Selecionar produtos componentes',
                'complexidade' => 'baixa',
                'tempo_estimado' => '30 minutos por kit',
            ],
            'assinatura' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'Vindi, Asaas integração',
                'como_fazer' => 'Integrar com gateway de recorrência via API ou app do marketplace',
                'complexidade' => 'media',
                'tempo_estimado' => '1-2 dias',
                'custo' => 'R$ 99-299/mês + taxa por transação',
            ],
            'avise_me' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Configurações > Produtos > Ativar "Avise-me quando chegar"',
                'complexidade' => 'baixa',
                'tempo_estimado' => '15 minutos',
            ],
            'cupom' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Marketing > Cupons > Criar novo cupom',
                'complexidade' => 'baixa',
                'tempo_estimado' => '10 minutos',
            ],
            'frete_gratis_condicional' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Configurações > Frete > Criar regra de frete grátis com valor mínimo',
                'complexidade' => 'baixa',
                'tempo_estimado' => '20 minutos',
            ],
            'email_carrinho_abandonado' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Marketing > Automações > Configurar email de carrinho abandonado',
                'complexidade' => 'baixa',
                'tempo_estimado' => '1 hora',
            ],
            'quiz_personalizado' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'Typeform (embed), Leadster',
                'como_fazer' => 'Criar quiz em ferramenta externa e incorporar via HTML/iframe',
                'complexidade' => 'media',
                'tempo_estimado' => '4-8 horas',
            ],
        ],
    ],

    'woocommerce' => [
        'nome' => 'WooCommerce',
        'complexidade_geral' => 'media',
        'possui_app_store' => true,
        'custo_apps_medio' => 'US$ 50-200/ano',
        'recursos' => [
            'kits' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'WooCommerce Product Bundles, YITH Product Bundles',
                'como_fazer' => 'Instalar plugin de bundles e configurar produtos agrupados',
                'complexidade' => 'media',
                'tempo_estimado' => '2-4 horas',
                'custo' => 'US$ 49-99/ano',
            ],
            'assinatura' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'WooCommerce Subscriptions, SUMO Subscriptions',
                'como_fazer' => 'Instalar plugin de subscriptions e configurar produtos recorrentes',
                'complexidade' => 'media',
                'tempo_estimado' => '4-8 horas',
                'custo' => 'US$ 199/ano',
            ],
            'avise_me' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'YITH WooCommerce Wishlist, Back In Stock Notifier',
                'como_fazer' => 'Instalar plugin de notificação de estoque',
                'complexidade' => 'baixa',
                'tempo_estimado' => '1-2 horas',
                'custo' => 'Gratuito até US$ 79/ano',
            ],
            'cupom' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'Marketing > Cupons > Adicionar cupom',
                'complexidade' => 'baixa',
                'tempo_estimado' => '10 minutos',
            ],
            'frete_gratis_condicional' => [
                'disponivel' => true,
                'nativo' => true,
                'como_fazer' => 'WooCommerce > Configurações > Entrega > Adicionar zona com frete grátis condicional',
                'complexidade' => 'baixa',
                'tempo_estimado' => '30 minutos',
            ],
            'email_carrinho_abandonado' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'AutomateWoo, Abandoned Cart Pro, Retainful',
                'como_fazer' => 'Instalar plugin de recuperação de carrinho e configurar sequência de emails',
                'complexidade' => 'media',
                'tempo_estimado' => '2-4 horas',
                'custo' => 'US$ 99-199/ano',
            ],
            'quiz_personalizado' => [
                'disponivel' => true,
                'nativo' => false,
                'app_recomendado' => 'Quiz Cat, WP Quiz, Typeform',
                'como_fazer' => 'Instalar plugin de quiz ou integrar ferramenta externa via shortcode',
                'complexidade' => 'media',
                'tempo_estimado' => '4-8 horas',
                'custo' => 'Gratuito até US$ 99/ano',
            ],
        ],
    ],
];
